[[mgr.prepend_keymap]]
on = "y"
run = ["plugin copy-file-contents"]
desc = "Copy file contents to clipboard"

[[mgr.prepend_keymap]]
on = "Y"
run = ["yank"]
desc = "Yank (copy) files"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = ["plugin smart-enter"]
desc = "Smart enter: open file / enter dir"

