- hosts: localhost
  gather_facts: yes

  tasks:
    # ------- macOS: brew -------
    - name: Base packages on macOS (brew)
      homebrew:
        name:
          - tmux
          - bat
          - fzf
          - ripgrep
          - fd
          - jq
          - poppler
          - starship
          - zoxide
          - zsh-autosuggestions
          - zsh-syntax-highlighting
        state: present
      when: ansible_facts['os_family'] == "Darwin"

    # ------- Ubuntu/Debian: apt -------
    - name: Base packages on Ubuntu/Debian (apt)
      apt:
        name:
          - git
          - zsh
          - tmux
          - bat
          - fzf
          - ripgrep
          - fd-find
          - jq
          - poppler-utils
          - starship
          - zoxide
          - zsh-autosuggestions
          - zsh-syntax-highlighting
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
