palette = "custom"
format = "$hostname $directory$git_branch$git_status\u2009$cmd_duration$fill$time$line_break$character"

[directory]
truncation_length = 100
truncate_to_repo = false
format = "[$path]($style)"
style = "fg:accent"

[git_branch]
format = " [git:](fg:#F5F5F5)\\([$branch]($style)\\)"
symbol = ""
style  = "fg:accent"

[git_status]
format = "[\\[](fg:white)[$all_status$ahead_behind]($style)[\\]](fg:white)"
style  = "fg:accent"
disabled = false

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[$time]($style)"
style = "fg:#F5F5F5"
utc_time_offset = "local"

[cmd_duration]
min_time = 500
format = "took [$duration]($style)"
style = "fg:#F5F5F5"
show_milliseconds = false

[fill]
symbol = " "
style = "fg:white"

[character]
success_symbol = "[\uF101 ](fg:white)"
error_symbol   = "[\uF101 ](fg:white)"
vicmd_symbol   = "[\uF101 ](fg:white)"

[username]
show_always = true
format = "[$user](fg:white)"

[hostname]
ssh_only = false
format = "[@$hostname](fg:white)"

[palettes.custom]
accent = "#E33A33"
white = "#ffffff"
