palette = "custom"
format = "$hostname $directory$git_branch$git_status\u2009$cmd_duration$fill$time$line_break$character"

[directory]
truncation_length = 100
truncate_to_repo = false
format = "[$path]($style)"
style = "fg:path"

[git_branch]
format = " [git:](fg:git_blue)[\\(](fg:git_blue)[$branch]($style)[\\)](fg:git_blue)"
symbol = ""
style  = "fg:git_red"

[git_status]
# 変更点：カッコ全体を () で包み、$all_status/$ahead_behind が空のときは非表示
format = "([\\[](fg:git_blue)[$all_status$ahead_behind]($style)[\\]](fg:git_blue))"
style  = "fg:git_red"
disabled = false

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[$time]($style)"
style = "fg:clock"
utc_time_offset = "local"

[cmd_duration]
min_time = 500
format = "[took $duration]($style)"
style = "fg:clock"
show_milliseconds = false

[fill]
symbol = " "
style = "fg:white"

[character]
format = "$symbol\u2009"
success_symbol = "[\uF105](fg:arrow)"
error_symbol   = "[\uF105](fg:arrow)"
vicmd_symbol   = "[\uF105](fg:arrow)"

[hostname]
ssh_only = false
format = "[@$hostname]($style)"
style = "fg:arrow"

[palettes.custom]
path     = "#56B6C2"
git_blue = "#65b1cd"
git_red  = "#d84f76"
arrow    = "#98C379"
white    = "#e0def4"
clock    = "#b1acde"
