palette = "custom"
format = "$hostname $directory$git_branch$git_status\u2009$cmd_duration$fill$time$line_break$character"

[directory]
truncation_length = 100
truncate_to_repo = false
format = "[$path]($style)"
style = "fg:path"

[git_branch]
format = " [git:](fg:git_label)[\\(](fg:git_label)[$branch]($style)[\\)](fg:git_label)"
symbol = ""
style  = "fg:branch"

[git_status]
format = "[\\[](fg:git_label)[$all_status$ahead_behind]($style)[\\]](fg:git_label)"
style  = "fg:accent"
disabled = false

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[$time]($style)"
style = "fg:#F5F5F5"
utc_time_offset = "local"

[cmd_duration]
min_time = 500
format = "took [$duration]($style)"
style = "fg:#F5F5F5"
show_milliseconds = false

[fill]
symbol = " "
style = "fg:white"

[character]
format = "$symbol\u2009"
success_symbol = "[\uF105](fg:arrow)"
error_symbol   = "[\uF105](fg:arrow)"
vicmd_symbol   = "[\uF105](fg:arrow)"

[username]
show_always = true
format = "[$user](fg:white)"

[hostname]
ssh_only = false
format = "[@$hostname]($style)"
style = "fg:arrow"

[palettes.custom]
accent = "#E33A33"
white = "#ffffff"
path = "#56B6C2"
git_label = "#5FAAE8"
branch = "#D0666F"
arrow = "#98C379"
